
name: "Build"
on:
  pull_request:
  push:
jobs:
  nix-build:
    name: "Nix"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: DeterminateSystems/flake-checker-action@main
    - run: nix build
    - run: nix run . -- -V


